### ISSUE TITLE
Rename "Other..." to Bring your Own Image for unlisted_choice

### ISSUE THREAD

**Issue by batpad** [2i2c-org/jupyterhub-fancy-profiles#105]
### Context

As per #104 rename Other... to "Bring your Own Image" in the select drop-down when `unlisted_choice` is enabled.

Alternatively, make this text customizable, but default to "Bring your Own Image".

**Comment by batpad** [comment]
Hmm.. why do I have a memory of this already being supposedly configurable? Going to poke around.

**Comment by batpad** [comment]
Ah yes there is `display_name_in_choices` that should work - https://github.com/2i2c-org/jupyterhub-fancy-profiles/blob/main/jupyterhub_config.py#L59

So, this should just require a config change in the `2i2c-org/infrastructure` repository to change the name.

@maxrjones I do agree that the repetition of this config across multiple profiles could get tedious. Let's chat about that and see if there's a good solution we can propose.

For now, I'll make a PR to `2i2c-org/infrastructure` with the config change and can close this when it's deployed.

**Comment by batpad** [comment]
This should be fixed on the VEDA hub! Closing here. @maxrjones please re-open if something does not work as expected.

**Comment by cboettig** [comment]
err, I'm still seeing "Other..." as the tag here.  Maybe I have not upgraded to the newest version of fancy-profiles properly?  I have set the image tag to `z2jh-v4.0.0-fancy-profiles-sha-2ad902d` .

**Comment by batpad** [comment]
@cboettig ah sorry, I should have made the solution more clear. This does not require any updates to `jupyterhub-fancy-profiles` - this is just a configuration change to add a `display_name_in_choices` parameter. You can see the change we made here: https://github.com/2i2c-org/infrastructure/pull/5640/files#diff-505f7d46e12dd33d4801d07e7be35c722ec2e3b73764ca261f4832b8f559a10eR131

Let me know if that works for you!

**Comment by cboettig** [comment]
Oh that's lovely!  :tada: :tada:

![Image](https://github.com/user-attachments/assets/d87212ef-0c5a-4fbe-ae79-51042fcdd414)

(and sorry I should have read closer before!)
